name: Verify Changelog

on:
  pull_request:

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check changelog
        run: |
          git fetch origin ${{ github.base_ref }}:base
          if ! git diff --name-only base...HEAD | grep -q '^CHANGELOG.md$'; then
            echo "::error::CHANGELOG.md must be updated"
            exit 1
          fi
