name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install tools
        run: npm install --no-save eslint@8 stylelint cspell js-yaml
      - name: Schema version check
        run: npm run check:schema
      - name: ESLint
        run: npx eslint@8 --no-eslintrc --env browser --env es2021 script.js
      - name: stylelint
        run: npx stylelint styles.css
      - name: cSpell
        run: npx cspell README.md terms.json
      - name: Link checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: --no-cache terms.json
