name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install linters
        run: npm install --no-save eslint@8 stylelint cspell remark-cli remark-lint remark-lint-prohibited-strings remark-lint-write-good unist-util-visit mdast-util-to-string
      - name: ESLint
        run: npx eslint@8 --no-eslintrc --env browser --env es2021 script.js
      - name: stylelint
        run: npx stylelint styles.css
      - name: cSpell
        run: npx cspell README.md terms.json
      - name: remark-lint
        run: npx remark .
      - name: Link checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: --no-cache terms.json
