name: PR Checklist

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  checklist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const core = require('@actions/core');
            const body = context.payload.pull_request.body || "";
            const required = [
              'Added/updated terms in `data.json`',
              'Ran tests (`npm test`)',
              'Updated documentation if needed',
              'Definition updated',
              'Examples verified',
              'Tags validated'
            ];
            const missing = required.filter(item => {
              const escaped = item.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
              const pattern = new RegExp(`- \\[x\\] ${escaped}`, 'i');
              return !pattern.test(body);
            });
            if (missing.length) {
              core.setFailed(`Please check the following items: ${missing.join(', ')}`);
            }
