name: RAG evaluation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  rag-eval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: pip install -r scripts/rag-eval-requirements.txt
      - name: Run RAG evaluation
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scripts/rag_eval.py
      - name: Upload evaluation log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rag-eval
          path: logs/rag-eval.json
      - name: Create issue on regression
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'RAG evaluation regression',
              body: 'Nightly RAG evaluation dropped below threshold. See artifact rag-eval for details.'
            })
